-- ==========================================
-- NSL Daily Activity Log System
-- Version 1.0
-- ==========================================

--------------------------------------------------
-- USERS
--------------------------------------------------
SELECT* FROM USERS;
CREATE TABLE users (
    user_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    employee_code VARCHAR2(20) UNIQUE NOT NULL,

    full_name VARCHAR2(100) NOT NULL,

    role VARCHAR2(20) NOT NULL,

    department VARCHAR2(100),

    phone VARCHAR2(20),

    password_hash VARCHAR2(255),

    is_active CHAR(1) DEFAULT 'Y'
        CHECK (is_active IN ('Y','N')),

    created_at DATE DEFAULT SYSDATE
);

--------------------------------------------------
-- SERVICE CATEGORIES
--------------------------------------------------

CREATE TABLE service_categories (
    category_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    category_name VARCHAR2(200) NOT NULL,

    is_active CHAR(1) DEFAULT 'Y'
        CHECK (is_active IN ('Y','N'))
);

--------------------------------------------------
-- SERVICES
--------------------------------------------------

CREATE TABLE services (
    service_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    category_id NUMBER NOT NULL,

    service_name VARCHAR2(300) NOT NULL,

    is_active CHAR(1) DEFAULT 'Y'
        CHECK (is_active IN ('Y','N')),

    CONSTRAINT fk_service_category
        FOREIGN KEY(category_id)
        REFERENCES service_categories(category_id)
);

--------------------------------------------------
-- DAILY LOGS
--------------------------------------------------

CREATE TABLE daily_logs (

    log_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    user_id NUMBER NOT NULL,

    service_id NUMBER NOT NULL,

    log_date DATE NOT NULL,

    activity_description VARCHAR2(2000),

    start_time TIMESTAMP,

    end_time TIMESTAMP,

    outcome VARCHAR2(2000),

    remark VARCHAR2(1000),

    status VARCHAR2(20)
        DEFAULT 'DRAFT'
        CHECK (
            status IN (
                'DRAFT',
                'SUBMITTED',
                'APPROVED',
                'REJECTED'
            )
        ),

    created_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_daily_log_user
        FOREIGN KEY(user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_daily_log_service
        FOREIGN KEY(service_id)
        REFERENCES services(service_id)
);

--------------------------------------------------
-- APPROVALS
--------------------------------------------------

CREATE TABLE approvals (

    approval_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    log_id NUMBER NOT NULL,

    approved_by NUMBER NOT NULL,

    approval_status VARCHAR2(20)
        CHECK (
            approval_status IN (
                'APPROVED',
                'REJECTED'
            )
        ),

    comments VARCHAR2(1000),

    approval_date DATE DEFAULT SYSDATE,

    CONSTRAINT fk_approval_log
        FOREIGN KEY(log_id)
        REFERENCES daily_logs(log_id),

    CONSTRAINT fk_approval_user
        FOREIGN KEY(approved_by)
        REFERENCES users(user_id)
);


CREATE TABLE log_attachments (
    attachment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    log_id NUMBER NOT NULL,
    file_name VARCHAR2(255),
    file_path VARCHAR2(500),
    uploaded_at DATE DEFAULT SYSDATE,

    CONSTRAINT pk_log_attachments
        PRIMARY KEY (attachment_id),

    CONSTRAINT fk_attachment_log
        FOREIGN KEY (log_id)
        REFERENCES daily_logs(log_id)
);

CREATE TABLE log_activities (

    log_activity_id NUMBER
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,

    log_id NUMBER NOT NULL,

    activity_id NUMBER NOT NULL,

    quantity_completed NUMBER,

    duration_minutes NUMBER,

    quality_percent NUMBER(5,2),

    created_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_log_activity_log
        FOREIGN KEY (log_id)
        REFERENCES daily_logs(log_id),

    CONSTRAINT fk_log_activity_template
        FOREIGN KEY (activity_id)
        REFERENCES activity_templates(activity_id)
);

CREATE TABLE task_assignments (
    task_id NUMBER PRIMARY KEY,

    assigned_by NUMBER NOT NULL,

    assigned_to NUMBER NOT NULL,

    title VARCHAR2(200) NOT NULL,

    description VARCHAR2(1000),

    due_date DATE,

    status VARCHAR2(20) DEFAULT 'PENDING',

    created_at DATE DEFAULT SYSDATE
);

CREATE SEQUENCE task_assignments_seq
START WITH 1
INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_task_assignments
BEFORE INSERT ON task_assignments
FOR EACH ROW
BEGIN
    IF :NEW.task_id IS NULL THEN
        SELECT task_assignments_seq.NEXTVAL
        INTO :NEW.task_id
        FROM dual;
    END IF;
END;
/
CREATE TABLE performance_goals (

    goal_id NUMBER PRIMARY KEY,

    user_id NUMBER NOT NULL,

    target_score NUMBER NOT NULL,

    period VARCHAR2(20),

    start_date DATE,

    end_date DATE,

    created_by NUMBER,

    created_at DATE DEFAULT SYSDATE
);

CREATE SEQUENCE performance_goals_seq
START WITH 1
INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_performance_goals
BEFORE INSERT ON performance_goals
FOR EACH ROW
BEGIN
    IF :NEW.goal_id IS NULL THEN
        SELECT performance_goals_seq.NEXTVAL
        INTO :NEW.goal_id
        FROM dual;
    END IF;
END;
/
DESC task_assignments;
SELECT trigger_name
FROM user_triggers
WHERE table_name = 'TASK_ASSIGNMENTS';
COMMIT;

